name: koala
description: A poor man's version of a pandas Dataframe. Collect, access & manipulate related data.
repository: https://github.com/w2sv/koala
version: 0.1.1

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  csv: ^5.0.1
  jiffy: ^6.0.0

dev_dependencies:
  coverage: ^1.6.0
  test: ^1.21.5